version: '3'

services:
  proxy:
    build:
      context: ./nginx-proxy
    env_file:
      - ./.env/.env
    restart: always
    links:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/logs/nginx-proxy:/var/log/nginx

  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    env_file:
      - ./.env/.env
    environment:
      VIRTUAL_HOST: localhost
      CERT_NAME: localhost
      HTTPS_METHOD: noredirect
    links:
      - app
    volumes:
      - ./nginx/conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/logs/nginx:/var/log/nginx
      - ./data/html/app:/var/www/html

  app:
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
      args:
        PHP_IMAGE_VERSION: fpm-alpine
    ports:
      - 9000:9000
    env_file:
      - ./.env/.env
    links:
      - db
    volumes:
      - ./data/html/app:/var/www/html

  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    expose:
      - 3306
    env_file:
      - ./.env/.env
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
      - ./mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./mariadb/my.cnf:/etc/mysql/conf.d/my.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    env_file:
      - ./.env/.env
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
    links:
      - db
    volumes:
      - ./phpmyadmin/config/config.inc.php:/etc/phpmyadmin/config.user.inc.php

volumes:
  db-data:
